[package]
name = "btrd"
version = "0.1.0"
authors = ["Daniel Xu <dxu@dxuuu.xyz>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
log = "0.4"
pom = "3.2"
rustyline = "7.1"
rustyline-derive = "0.4"
simplelog = "0.9"
structopt = "0.3"
